### ISSUE TITLE
Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by FuzzyWobble** [FarazzShaikh/THREE-CustomShaderMaterial#1]
I'm very new to shaders. Trying to get this to work. Made a test project here.

[https://ambiguous-pond-punishment.glitch.me/](https://ambiguous-pond-punishment.glitch.me/)
^^ live link

[https://glitch.com/edit/#!/join/3d68ed5c-fffa-4975-91ef-611a7fecfa54](https://glitch.com/edit/#!/join/3d68ed5c-fffa-4975-91ef-611a7fecfa54)
^^ editable link

Any idea what the issue is? Thanks!

**Comment by FarazzShaikh** [comment]
@FuzzyWobble the issue seems to be that you are not passing any uniforms into the uniforms parameter in the constructor in line _**125**_ of **_"my-js.js"_** :
```
 csm =  new CustomShaderMaterial({
    baseMaterial:   TYPES.NORMAL,
    vShader:        [main, global],
    uniforms:       [],
    options:        {}
  });
```
Instead change to: 
```
 csm =  new CustomShaderMaterial({
    baseMaterial:   TYPES.NORMAL,
    vShader:        [main, global],
    uniforms:       [{time: {value: 0}}],
    options:        {}
  });
```
The _uniform_ parameter is an array of objects where each object is in the format - `{unifromName: {value: initialValue}}`.

Please confirm if this fixed your issue. Thank you. 😄

**Comment by FarazzShaikh** [comment]
@FuzzyWobble I am closing this issue for now. Please get back to me, if this is still a problem I will reopen this issue.

**Comment by FarazzShaikh** [comment]
@FuzzyWobble I am closing this issue for now. Please get back to me, if this is still a problem I will reopen this issue.
