### ISSUE TITLE
Extended meshBasicMaterial does not have access to cameraPosition uniform

### ISSUE THREAD

**Issue by chasedavis** [FarazzShaikh/THREE-CustomShaderMaterial#41]
This is really minor and maybe not a CSM issue but rather a Three.js issue but I thought I would log it. 

[Three.js docs list](https://threejs.org/docs/#api/en/renderers/webgl/WebGLProgram) `cameraPosition` as a uniform accessible from shader. 

With that said, `cameraPosition` is not accessible from shader if the base material in CSM is `MeshBasicMaterial`. The value of `cameraPosition` is just `vec3(0,0,0)`. 

I don't think it's the sort of issue you'd run into with vanilla shaderMaterials in three however because you wouldn't be using MeshBasicMaterial in the first place, but maybe it's the fact that it's being extended which is causing it?

[This issue](https://discourse.threejs.org/t/why-cameraposition-in-pointsmaterial-shader-set-to-0-0-0/29152) on three's discourse explains the relevant source a bit better. 

Issue is demonstrated here where I'm setting csm_DiffuseColor to `vec4(normalize(cameraPosition))` and you can see that it's all black when base is `MeshBasicMaterial`

https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/assets/10068755/f4bbf42a-1d45-4899-b638-636f008c00c5

**Comment by FarazzShaikh** [comment]
I've looked into it. Unfortunately, the fix is not as simple as just setting `isShaderMaterial` to true, being a ShaderMaterial means the WebGLRenderer handles the material differently in terms of creation, disposal and caching. The main issue being that the pre-build shader IDs are hardcoded into the renderer here: 
https://github.com/mrdoob/three.js/blob/74939a623cf06ef68b6eb3e2c66f36d127f8bd1a/src/renderers/webgl/WebGLPrograms.js#L20

This means that setting `isShaderMaterial` runs some code ment for ShaderMaterial and some code meant for baseMaterial. Reuslting in things breaking. 

I think the best thing for CSM is to simply pretend to be its baseMaterial all the way through. 

It is a shame ThreeJS doesnt have a first class system for material extentions but this is the best were going to get for now.

**Comment by chasedavis** [comment]
Thanks for looking into it @FarazzShaikh. The good news is that there are plenty of workarounds but I wanted to file in case it helped to improve CSM.

Appreciate it!

**Comment by FarazzShaikh** [comment]
Appreciate you using it! Glad to look into any possible improvements 😄
