### ISSUE TITLE
Couldn't extend `<MeshReflectorMaterial/>` from `drei`

### ISSUE THREAD

**Issue by nhtoby311** [FarazzShaikh/THREE-CustomShaderMaterial#45]
I tried to extend the `<MeshReflectorMaterial/>` from `drei`, but it results in black material. I'm not sure what cause the problem, as I did haven't used the fragment shader yet. 

```tsx
<MeshReflectorMaterial
  ref={setMaterialRef}
  ...
/>

<mesh position={[0, -0, 0]} rotation-x={-Math.PI / 2}>
  <planeGeometry args={[50, 50]} />
  {materialRef && (
    <OceanMaterial
      baseMaterial={materialRef}
      ...
    />
  )}
</mesh>
```

I have replicate the issue here: https://codesandbox.io/p/sandbox/ocean-material-889c76?file=%2Fsrc%2FScene.tsx%3A2%2C10-2%2C31

**Comment by FarazzShaikh** [comment]
`MeshReflectorMaterial` is an already extended material. i.e. it already extends `MeshStandardMaterial` to add its functionality. 

Unfortunately, there is no feasable way to detetect whats been changed already, and no garuntee that an aleady extended material will preserve the shader chunks that CSM uses to do its thing. 

You have a couple options here:
- Replicated `MeshReflectorMaterial` from scratch yourself but using CSM (easiest)
- Figure out what `MeshReflectorMaterial` changes, where, and write your own `patchMaps` for your usecase 

If you think that this issue can be fixed in CSM, please re-open the issue and submit a fix proposal or PR.
