### ISSUE TITLE
Cannot use both csm_DiffuseColor and csm_FragColor in if/else

### ISSUE THREAD

**Issue by tresabhi** [FarazzShaikh/THREE-CustomShaderMaterial#48]
When in opaque mode, my shader uses diffuse color to allow there to be lighting on the mesh. When not in opaque mode, my shader forms a neon overlay. But using both, even in an exclusive if/else statement, doesn't work. Heck, even commenting "// csm_FragColor" anywhere breaks the code.

```glsl
uniform bool opaque;

void main() {
  if (opaque) {
    csm_DiffuseColor = vec4(1.0);
  else {
    csm_FragColor = vec4(1.0, 0.0, 0.0, 0.5);
  }
}
```

**Comment by FarazzShaikh** [comment]
Weird, yes the first part of your question is a bug. CSM to prove https://codesandbox.io/s/awesome-robinson-dz3p99?file=/src/App.tsx

> Heck, even commenting "// csm_FragColor" anywhere breaks the code.

Not sure what you mean. Comments are stripped internally, so they shoudlnt have any effect. Here is a CSB with it working as expected with a `// csm_FragColor` https://codesandbox.io/s/sad-booth-ttjwg8?file=/src/App.tsx

**Comment by FarazzShaikh** [comment]
Temporary workaround is to use shader replacement like so: https://codesandbox.io/s/nervous-agnesi-mz8yzj?file=/src/App.tsx:897-926

Doing this does not seem to have any performance implications. However, the bug should be fixed in the next update.

**Comment by tresabhi** [comment]
Weird, comments did break them in my case, oh well. Glad to see such a rapid fix 😄, thanks!

**Comment by FarazzShaikh** [comment]
So this issue is more complicated to solve than is worth. It basically requires smarter code analysis to determeine if `csm_FragColor` must take effect. This will add complexity that isnt worth it

To work around this v6 introduces `csm_UnlitFac`. It is a mix factor between lit and unit materials. Your `if` block can be rewritten as the following with `csm_UnlitFac` in v6:

```glsl
uniform bool opaque;

void main() {
  csm_DiffuseColor = vec4(1.0);
  csm_FragColor = vec4(1.0, 0.0, 0.0, 0.5);

  csm_UnlitFac = opaque ? 0.0 : 1.0;
}
```

`csm_UnlitFac` can also be a gradient or any float, letting you mix between lit and unlit in the same shader.
